# -*- coding: utf-8 -*-
"""Tugas_SPK_TOPSIS_Linda syahrunp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_BEaSJt4DDYPTkss2JzH_UkXCH9emWj
"""

import numpy as np
import pandas as pd

alternatif = ["Laptop A", "Laptop B", "Laptop C"]
kriteria = ["Harga", "RAM", "Storage", "Desain"]
is_benefit = [False, True, True, True] # False = Cost, True = Benefit

X = np.array([
    [10, 8, 5, 7],
    [8, 16, 10, 9],
    [12, 12, 8, 6]
])

W = np.array([5, 4, 3, 2])

def topsis(matrix, weights, benefit_mask):
    norm_matrix = matrix / np.sqrt((matrix**2).sum(axis=0))

    weighted_matrix = norm_matrix * weights

    a_plus = []
    a_minus = []
    for i in range(len(benefit_mask)):
        if benefit_mask[i]:
            a_plus.append(np.max(weighted_matrix[:, i]))
            a_minus.append(np.min(weighted_matrix[:, i]))
        else:
            a_plus.append(np.min(weighted_matrix[:, i]))
            a_minus.append(np.max(weighted_matrix[:, i]))

    d_plus = np.sqrt(((weighted_matrix - a_plus)**2).sum(axis=1))
    d_minus = np.sqrt(((weighted_matrix - a_minus)**2).sum(axis=1))

    v_score = d_minus / (d_plus + d_minus)
    return v_score

hasil_v = topsis(X, W, is_benefit)

df_hasil = pd.DataFrame({
    'Alternatif': alternatif,
    'Skor_V': hasil_v
}).sort_values(by='Skor_V', ascending=False)

print("Hasil Perangkingan TOPSIS:")
print(df_hasil)