# -*- coding: utf-8 -*-
"""Tugas_Profile_Matching_Lindasyahrun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kelSlNrK2OWLh4xXc0FfDuxKRQPRw-PQ
"""

import pandas as pd
import numpy as np

kandidat = ['Andi', 'Budi', 'Cici']
kriteria = ['Kecerdasan', 'Sikap', 'Komunikasi', 'Kerjasama']

data_nilai = np.array([
    [4, 3, 3, 5], # Andi
    [3, 4, 4, 3], # Budi
    [5, 5, 3, 4]  # Cici
])

target = np.array([4, 4, 3, 4])

gap = data_nilai - target

def hitung_bobot(gap_val):
    tabel_bobot = {
        0: 5,   # Tidak ada selisih
        1: 4.5, # Kelebihan 1 tingkat
        -1: 4,  # Kekurangan 1 tingkat
        2: 3.5, # Kelebihan 2 tingkat
        -2: 3,  # Kekurangan 2 tingkat
        3: 2.5, # Kelebihan 3 tingkat
        -3: 2,  # Kekurangan 3 tingkat
        4: 1.5, # Kelebihan 4 tingkat
        -4: 1   # Kekurangan 4 tingkat
    }
    return tabel_bobot.get(gap_val, 1)

bobot_gap = np.vectorize(hitung_bobot)(gap)


cf_indices = [0, 1]
sf_indices = [2, 3]

n_cf = bobot_gap[:, cf_indices].mean(axis=1)
n_sf = bobot_gap[:, sf_indices].mean(axis=1)

total_score = (0.6 * n_cf) + (0.4 * n_sf)

df_hasil = pd.DataFrame({
    'Nama': kandidat,
    'Core_Factor': n_cf,
    'Secondary_Factor': n_sf,
    'Total_Skor': total_score
}).sort_values(by='Total_Skor', ascending=False)

print("Hasil Perangkingan Profile Matching:")
print(df_hasil)